# Generated by Django 6.0.3 on 2026-04-08 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0006_experince_currentlly_experince_date_end_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='about_me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aboutMe.aboutme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
