# Generated by Django 6.0.3 on 2026-03-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0002_certificate_experince_membership_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='about_me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aboutMe.aboutme'),
            preserve_default=False,
        ),
    ]
