# Generated by Django 6.0.3 on 2026-03-30 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0003_education_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='about_me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aboutMe.aboutme'),
            preserve_default=False,
        ),
    ]
