# Generated by Django 6.0.3 on 2026-03-30 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0004_certificate_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='experince',
            name='about_me',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aboutMe.aboutme'),
            preserve_default=False,
        ),
    ]
