# Generated by Django 6.0.3 on 2026-03-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutMe', '0005_experince_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='experince',
            name='currentlly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experince',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experince',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
